#!/bin/bash
#
# Utility to lookup window position and size and map the Wacom tablet to it.
#
# Dependencies:
#   - xwininfo
#   - xsetwacom

# Tablet drawing application (use xprop and copy WM_NAME(STRING))
APPLICATION_NAME="Lorien v0.6.0"

# xsetwacom list devices
STYLUS_NAME="Wacom One by Wacom M Pen stylus"

# Rotate none|half|cw|ccw
STYLUS_ROTATION="none"

# X, Y, W, H
dimensions=()

# output from: xwininfo | grep
#
#  Absolute upper-left X:  3740
#  Absolute upper-left Y:  735
#  Width: 1377
#  Height: 702
while IFS=: read -r _ value; do
	value=$(echo -e "${value}" | tr -d "[:space:]")
	dimensions+=("$value")
done < <(xwininfo -name "$APPLICATION_NAME" | grep -e "Absolute" -e "Width" -e "Height")

# Argument order is W H X Y
xsetwacom set "$STYLUS_NAME" MapToOutput "${dimensions[2]}x${dimensions[3]}+${dimensions[0]}+${dimensions[1]}"

if [ $# -gt 0 ]; then
	STYLUS_ROTATION="$1"
fi

xsetwacom set "$STYLUS_NAME" Rotate "$STYLUS_ROTATION"
