#!/bin/bash
#
# Utility to lookup window position and size and map the Wacom tablet to it.
#
# Dependencies:
#   - xwininfo
#   - xsetwacom

# Name of the executable script.
EXECUTABLE="$(basename "$0")"
# Tablet drawing application (use xprop and copy WM_NAME(STRING))
APPLICATION_NAME="Lorien v0.6.0"
# xsetwacom list devices
STYLUS_NAME="Wacom One by Wacom M Pen stylus"
# Rotate none|half|cw|ccw
TABLET_ROTATION="none"

# Getopts
OPTSTRING=":a:r:s:h"
while getopts "$OPTSTRING" option; do
	case "$option" in
	a)
		APPLICATION_NAME=$OPTARG
		;;
	r)
		TABLET_ROTATION=$OPTARG
		;;
	s)
		STYLUS_NAME=$OPTARG
		;;
	h)
		printf "Usage: %s [OPTIONS]\n" "$EXECUTABLE"
		printf "Maps your stylus to the specified window.\n"
		printf "Example: %s -a \"%s\" -r %s -s \"%s\"\n" "$EXECUTABLE" "$APPLICATION_NAME" "$TABLET_ROTATION" "$STYLUS_NAME"
		printf "Maps the stylus to the %s window using the default tablet orientation\n" "$APPLICATION_NAME"
		printf "\n"
		printf "Options:\n"
		printf " -a        name of application stylus should be mapped to\n"
		printf "           (use xprop to lookup the WM_NAME value)\n"
		printf "           (default: %s)\n" "$APPLICATION_NAME"
		printf " -r        how the table is rotated (i.e. orientation of tablet)\n"
		printf "           options: [none|half|cw|ccw] (default: none)\n"
		printf " -s        name of stylus (use xsetwacom list devices)\n"
		printf "           (default: %s)\n" "$STYLUS_NAME"

		exit 0
		;;
	?)
		printf "Usage: %s [OPTIONS]\n" "$EXECUTABLE"
		printf "Try '%s -h' for more information.\n" "$EXECUTABLE"
		exit 1
		;;
	esac
done

# Index mappings
X=0 Y=1 W=2 H=3
dimensions=()

# output from: xwininfo ... | grep ...
#
#  Absolute upper-left X:  3740
#  Absolute upper-left Y:  735
#  Width: 1377
#  Height: 702
while IFS=: read -r _ dimension; do
	dimension=$(echo -e "$dimension" | tr -d "[:space:]")
	dimensions+=("$dimension")
done < <(xwininfo -name "$APPLICATION_NAME" | grep -e "Absolute" -e "Width" -e "Height")

# Argument order is W H X Y
xsetwacom set "$STYLUS_NAME" MapToOutput "${dimensions[$W]}x${dimensions[$H]}+${dimensions[$X]}+${dimensions[$Y]}"

if [ $# -gt 0 ]; then
	TABLET_ROTATION="$1"
fi

xsetwacom set "$STYLUS_NAME" Rotate "$TABLET_ROTATION"
