#!/bin/bash
#
# Utility to lookup window position and size and map the Wacom tablet to it.
#
# Dependencies:
#   - xwininfo
#   - xsetwacom

# Tablet drawing application (use xprop and copy WM_NAME(STRING))
APPLICATION_NAME="Lorien v0.6.0"

# xsetwacom list devices
STYLUS_NAME="Wacom One by Wacom M Pen stylus"

# Rotate none|half|cw|ccw
TABLET_ROTATION="none"

# Index mappings
X=0 Y=1 W=2 H=3
dimensions=()

# output from: xwininfo ... | grep ...
#
#  Absolute upper-left X:  3740
#  Absolute upper-left Y:  735
#  Width: 1377
#  Height: 702
while IFS=: read -r _ dimension; do
	dimension=$(echo -e "$dimension" | tr -d "[:space:]")
	dimensions+=("$dimension")
done < <(xwininfo -name "$APPLICATION_NAME" | grep -e "Absolute" -e "Width" -e "Height")

# Argument order is W H X Y
xsetwacom set "$STYLUS_NAME" MapToOutput "${dimensions[$W]}x${dimensions[$H]}+${dimensions[$X]}+${dimensions[$Y]}"

if [ $# -gt 0 ]; then
	TABLET_ROTATION="$1"
fi

xsetwacom set "$STYLUS_NAME" Rotate "$TABLET_ROTATION"
